# Generated by Django 4.1.7 on 2023-05-13 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpreferences', '0002_rename_userprefernce_userpreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='currency',
            field=models.CharField(default='USD - United States Dollar', max_length=255, null=True),
        ),
    ]
