# Generated by Django 4.1.7 on 2023-05-06 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userincome', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userincome',
            options={'ordering': ['-date'], 'verbose_name_plural': 'User Income'},
        ),
    ]
